// Code generated by Kitex v0.12.2. DO NOT EDIT.

package connectionservice

import (
	connect "chatroom/kitex_gen/connect"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetConnectionDetail": kitex.NewMethodInfo(
		getConnectionDetailHandler,
		newGetConnectionDetailArgs,
		newGetConnectionDetailResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	connectionServiceServiceInfo                = NewServiceInfo()
	connectionServiceServiceInfoForClient       = NewServiceInfoForClient()
	connectionServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return connectionServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return connectionServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return connectionServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ConnectionService"
	handlerType := (*connect.ConnectionService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "rpc",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.12.2",
		Extra:           extra,
	}
	return svcInfo
}

func getConnectionDetailHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(connect.EmptyRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(connect.ConnectionService).GetConnectionDetail(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetConnectionDetailArgs:
		success, err := handler.(connect.ConnectionService).GetConnectionDetail(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetConnectionDetailResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetConnectionDetailArgs() interface{} {
	return &GetConnectionDetailArgs{}
}

func newGetConnectionDetailResult() interface{} {
	return &GetConnectionDetailResult{}
}

type GetConnectionDetailArgs struct {
	Req *connect.EmptyRequest
}

func (p *GetConnectionDetailArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(connect.EmptyRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetConnectionDetailArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetConnectionDetailArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetConnectionDetailArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetConnectionDetailArgs) Unmarshal(in []byte) error {
	msg := new(connect.EmptyRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetConnectionDetailArgs_Req_DEFAULT *connect.EmptyRequest

func (p *GetConnectionDetailArgs) GetReq() *connect.EmptyRequest {
	if !p.IsSetReq() {
		return GetConnectionDetailArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetConnectionDetailArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetConnectionDetailArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetConnectionDetailResult struct {
	Success *connect.ConnectionResponse
}

var GetConnectionDetailResult_Success_DEFAULT *connect.ConnectionResponse

func (p *GetConnectionDetailResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(connect.ConnectionResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetConnectionDetailResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetConnectionDetailResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetConnectionDetailResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetConnectionDetailResult) Unmarshal(in []byte) error {
	msg := new(connect.ConnectionResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetConnectionDetailResult) GetSuccess() *connect.ConnectionResponse {
	if !p.IsSetSuccess() {
		return GetConnectionDetailResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetConnectionDetailResult) SetSuccess(x interface{}) {
	p.Success = x.(*connect.ConnectionResponse)
}

func (p *GetConnectionDetailResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetConnectionDetailResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetConnectionDetail(ctx context.Context, Req *connect.EmptyRequest) (r *connect.ConnectionResponse, err error) {
	var _args GetConnectionDetailArgs
	_args.Req = Req
	var _result GetConnectionDetailResult
	if err = p.c.Call(ctx, "GetConnectionDetail", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
