// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"chatroom/config"
	"chatroom/controller"
	"chatroom/pkg/core"
)

// Injectors from wire.go:

func NewHttpInjector(conf *config.Config) *core.AppProvider {
	engine := core.NewGinServer()
	userController := controller.NewUserController()
	controllers := &controller.Controllers{
		User: userController,
	}
	appProvider := &core.AppProvider{
		Config:      conf,
		Engine:      engine,
		Controllers: controllers,
	}
	return appProvider
}
