// Code generated by Kitex v0.12.2. DO NOT EDIT.

package connectionservice

import (
	connect "chatroom/rpc/kitex_gen/connect"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetConnectionDetail": kitex.NewMethodInfo(
		getConnectionDetailHandler,
		newConnectionServiceGetConnectionDetailArgs,
		newConnectionServiceGetConnectionDetailResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	connectionServiceServiceInfo                = NewServiceInfo()
	connectionServiceServiceInfoForClient       = NewServiceInfoForClient()
	connectionServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return connectionServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return connectionServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return connectionServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ConnectionService"
	handlerType := (*connect.ConnectionService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "connect",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.12.2",
		Extra:           extra,
	}
	return svcInfo
}

func getConnectionDetailHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	_ = arg.(*connect.ConnectionServiceGetConnectionDetailArgs)
	realResult := result.(*connect.ConnectionServiceGetConnectionDetailResult)
	success, err := handler.(connect.ConnectionService).GetConnectionDetail(ctx)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newConnectionServiceGetConnectionDetailArgs() interface{} {
	return connect.NewConnectionServiceGetConnectionDetailArgs()
}

func newConnectionServiceGetConnectionDetailResult() interface{} {
	return connect.NewConnectionServiceGetConnectionDetailResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetConnectionDetail(ctx context.Context) (r *connect.ConnectionResponse, err error) {
	var _args connect.ConnectionServiceGetConnectionDetailArgs
	var _result connect.ConnectionServiceGetConnectionDetailResult
	if err = p.c.Call(ctx, "GetConnectionDetail", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
