// Code generated by Fastpb v0.0.2. DO NOT EDIT.

package connect

import (
	fmt "fmt"
	fastpb "github.com/cloudwego/fastpb"
)

var (
	_ = fmt.Errorf
	_ = fastpb.Skip
)

func (x *EmptyRequest) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
}

func (x *ConnectionResponse) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ConnectionResponse[number], err)
}

func (x *ConnectionResponse) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Chat, offset, err = fastpb.ReadInt32(buf, _type)
	return offset, err
}

func (x *ConnectionResponse) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	tmp, offset, err := fastpb.ReadInt32(buf, _type)
	x.Example = &tmp
	return offset, err
}

func (x *ConnectionResponse) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	tmp, offset, err := fastpb.ReadInt32(buf, _type)
	x.Num = &tmp
	return offset, err
}

func (x *EmptyRequest) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	return offset
}

func (x *ConnectionResponse) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	return offset
}

func (x *ConnectionResponse) fastWriteField1(buf []byte) (offset int) {
	if x.Chat == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 1, x.GetChat())
	return offset
}

func (x *ConnectionResponse) fastWriteField2(buf []byte) (offset int) {
	if x.Example == nil {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 2, x.GetExample())
	return offset
}

func (x *ConnectionResponse) fastWriteField3(buf []byte) (offset int) {
	if x.Num == nil {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 3, x.GetNum())
	return offset
}

func (x *EmptyRequest) Size() (n int) {
	if x == nil {
		return n
	}
	return n
}

func (x *ConnectionResponse) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	return n
}

func (x *ConnectionResponse) sizeField1() (n int) {
	if x.Chat == 0 {
		return n
	}
	n += fastpb.SizeInt32(1, x.GetChat())
	return n
}

func (x *ConnectionResponse) sizeField2() (n int) {
	if x.Example == nil {
		return n
	}
	n += fastpb.SizeInt32(2, x.GetExample())
	return n
}

func (x *ConnectionResponse) sizeField3() (n int) {
	if x.Num == nil {
		return n
	}
	n += fastpb.SizeInt32(3, x.GetNum())
	return n
}

var fieldIDToName_EmptyRequest = map[int32]string{}

var fieldIDToName_ConnectionResponse = map[int32]string{
	1: "Chat",
	2: "Example",
	3: "Num",
}
