// Code generated by Kitex v0.12.2. DO NOT EDIT.

package connectionservice

import (
	connect "chatroom/kitex_gen/rpc/connect"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetConnectionDetail(ctx context.Context, Req *connect.EmptyRequest, callOptions ...callopt.Option) (r *connect.ConnectionResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kConnectionServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kConnectionServiceClient struct {
	*kClient
}

func (p *kConnectionServiceClient) GetConnectionDetail(ctx context.Context, Req *connect.EmptyRequest, callOptions ...callopt.Option) (r *connect.ConnectionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetConnectionDetail(ctx, Req)
}
